version: '3.0'

services:

  alertmanager_bot:
    image: vortland/prometheus_bot
    environment:
      - PROXY_URL=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
    volumes:
      - ./config/:/config
    command:
      - '/prometheus_bot'
      - '-c=/config/config.yaml'
      - '-t=/config/default.tmpl'
    restart: always
    ports: 
      - 9087:9087