version: '3.0'

services:

  alertmanager_bot:
    image: registry.astralnalog.ru/library/prometheus_bot 
    environment:
      - Proxy_Url=none
      - Proxy_Username=none
      - Proxy_Password=none
    volumes:
      - ./config/:/config
    command:
      - '/prometheus_bot'
      - '-c=/config/config.yaml'
      - '-t=/config/default.tmpl'
    restart: always
